Add missing #include <string.h> in user interface files
Fixes several warnings when compiling under musl, e.g.

ui/irqbalance-ui.c: In function 'create_credentials_msg':
ui/irqbalance-ui.c:32:2: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
  memset(msg, 0, sizeof(struct msghdr));
  ^~~~~~
ui/irqbalance-ui.c:32:2: warning: incompatible implicit declaration of built-in function 'memset'
ui/irqbalance-ui.c:32:2: note: include '<string.h>' or provide a declaration of 'memset'
ui/irqbalance-ui.c: In function 'init_connection':
ui/irqbalance-ui.c:49:2: warning: incompatible implicit declaration of built-in function 'memset'
  memset(&addr, 0, sizeof(struct sockaddr_un));
  ^~~~~~

Signed-off-by: Timo Teräs <timo.teras@iki.fi>